markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false
permalink: /:year/:month/:day/:title
tag_layout: tag
tag_directory: tags
title: Joe Corcoran
description: Articles
url: https://corcoran.online
email: joe@corcoran.online
exclude: ["Gemfile", "Gemfile.lock", ".assets.rb", "assets", "bin", "vendor"]
plugins:
  - jekyll-gist
